src/main/c/seasocks/Credentials.h
src/main/c/seasocks/PrintfLogger.h
src/main/c/seasocks/WebSocket.h
src/main/c/seasocks/util/PathHandler.h

I am compiling project with gcc and params -Wextra, -pedantic -Weffc++, and there were wanings in these parts.

Fix for GCC warnings

---

.travis.yml

Just `make` added to build steps, this shows the compilation progress and possible build failures.

CI: Make added as extra step.

---

.travis.yml

Each compiler builds Debug and Release.

CI: Build types added to matrix

---

src/app/c/async_test.cpp
src/app/c/ws_test.cpp
src/app/c/ws_test_poll.cpp
src/main/c/Connection.cpp
src/main/c/seasocks/Server.h

Some minor fixes.

---

src/main/c/Connection.cpp
src/main/c/Logger.cpp
src/main/c/Server.cpp

Some constants made `constexpr`.

Constants made constexpr

---

CMakeLists.txt

Version set to latest release.

Version fixed

---

src/app/c/async_test.cpp
src/app/c/ph_test.cpp
src/app/c/serve.cpp
src/app/c/ws_echo.cpp
src/app/c/ws_test.cpp
src/app/c/ws_test_poll.cpp
src/main/c/Connection.cpp
src/main/c/Logger.cpp
src/main/c/internal/LogStream.h
src/main/c/seasocks/Connection.h
src/main/c/seasocks/Logger.h
src/main/c/seasocks/Request.cpp
src/main/c/seasocks/Request.h

Remaining enums changed to scoped enums (as mentioned in #42).

Remaining enums changed to scoped enums

---

src/app/c/CMakeLists.txt

Cleanup (see #48)

---

src/test/c/CMakeLists.txt
src/test/c/EmbeddedContentTests.cpp

Some tests for the embedded content generation (see #48).

Embedded content test

---

src/main/c/Connection.cpp
src/main/c/seasocks/Server.h

Missing override added (#53)

---

CMakeLists.txt

Debug flag removed

---

src/main/c/internal/.gitignore

Obsolete `.gitignore` file removed.

Obsolete gitignore file removed

---

src/main/c/CMakeLists.txt
src/main/web/CMakeLists.txt

Static library fix

---

.travis.yml

Gcc7 CI Build added - everything works fine there.

Gcc7 CI Build added

---

src/test/c/JsonTests.cpp
src/test/c/ResponseBuilderTests.cpp
src/test/c/catch.hpp

Catch updated to latest release (v1.9.6) and some updates accordingly.
(Accidentally) cleaned up some white spaces too.

Catch updated to latest release

---

src/main/c/StringUtil.cpp

Pull request for issue: Release mode build fails Werror-unused-result #114

Resolved ignoring return value error

---

src/app/c/CMakeLists.txt
src/app/c/multiserver.cpp
src/main/c/Server.cpp

This allows us to have multiple threads listening on the same port in
Linux. Also add an example demonstrating usage.

Server: add SO_REUSEPORT socket option if available

---

src/test/c/catch/catch2/catch.hpp

Cherry pick of #165, since GCC 12 is affected too.

Update Catch 2.13.9

---

CMakeLists.txt

Placeholder for "hey I'm thinking of doing a release, any complaints/can you remember what we do to get a release actually done" :)  Got a few emails asking "it's been two years"...

Bump the version to 1.4.5, ahead of a release

---

.github/workflows/ci.yml

Adds a CI build for latest Clang 15.

Add Clang 15 CI build

---

.github/workflows/ci.yml

Disable Clang 15 build

---

scripts/ci_setup_clang.sh

This is likely a mistake :smile:.

Use 'apt-get'

---

.github/workflows/ci.yml

Builds for the latest version of GCC and Clang.

Add GCC 13 and Clang 16 CI builds

---

CMakeLists.txt

A new release, mainly to ship #193 and #192.
I'm going to create tag and GH release once merged.

Release v1.4.6

---

.github/workflows/ci.yml

Adds a CI build for the latest GCC 14.

GCC 14 CI build

---

.github/workflows/ci.yml

CI builds for the latest versions of GCC and Clang.

Add GCC 15 and Clang 20 CI build

---

.github/workflows/ci.yml

CI build for the latest Clang release.

Add Clang 21 CI build
