mattgodbolt/seasocks

src/main/c/Connection.cpp
I need to controll Cache-Control for Response. For now, I made this changes.
What do you think?
Maybe I find better solution to add this headers as two atributes to seasocks::Response class with default values no-store and Expires = now().
=> Reponse can modify Cache-Control and Expires headers

.travis.yml
Install compilers through Travis Apt-addon.
Unfortunately, `sudo` is still required for installing valgrind, without it would be possible to run on (faster) travis containers.
=> Install compilers through Travis Apt-addon

.travis.yml
Just an addition to #12. Valgrind is installed through addon too - the build can run in a container.
=> Installing valgrind using apt addon

.gitignore, .travis.yml, CMakeLists.txt, cmake/CompilerCheck.cmake, cmake/Config.h.in, cmake/EmbeddedContent.cmake, cmake/Findgmock.cmake, cmake/Findgtest.cmake, src/app/c/CMakeLists.txt, src/main/c/CMakeLists.txt, src/test/c/CMakeLists.txt
This PR addes cmake as a second build tool.
- Building of library and apps
- Installation using `make install`
- Travis CI (Matrix using both)
- Generation of embedded content
- Testing compiler for `emplace()`
- Optional building / running of tests using gtest / gmock (default: `OFF`)
- Configure file - `Config.h` (based on a custom template in `cmake/`)
- Building tests on CI using cmake
Since google has merged gtest / gmock into one project - gmock depends on gtest though - i'm not sure how to handle this case on CI. It seems gmock requires gtest but doesn't ship it anymore in one bundle (?).
At the moment cmake will look for both if tests are enabled, otherwise there's no dependency on gtest / gmock if disabled.
The cmake builds will use it's own `Config.h` (`cmake` directory); it has …
=> CMake added

scripts/gen_embedded.py, src/main/c/Connection.cpp, src/main/c/Server.cpp, src/main/c/StringUtil.cpp, src/main/c/internal/PageRequest.h, src/main/c/seasocks/Connection.h
Since C++11 is checked, it's safe to use `nullptr` now.
=> NULL replaced by nullptr

CMakeLists.txt
The tests can be disabled now
To build without tests:
```
cmake -DUNITTESTS=OFF ..
```
Per *default* they are `ON`, so the option is optional.
=> Option for tests added

src/app/c/CMakeLists.txt
Just the parameter name used instead of `${ARGV0}` in the cmake macro.
=> Parameter name used in the macro

src/main/c/seasocks/ToString.h, src/test/c/HtmlTests.cpp, src/test/c/ToStringTests.cpp
This adds template specializations for integral- and string types.
The failing test of #31 is replaced by some new.
=> toString() for integral types implemented using std::to_string().

.travis.yml
Ci builds for _gcc 4.7_ to _gcc 6_ and _clang 3.6_ to _clang 3.8_ added. There's only a release build for each compiler to reduce the count of builds necessary.
=> Ci builds for more compilers added

src/main/c/Server.cpp, src/main/c/seasocks/Server.h
Thanks for Seasocks, works great for me so far!
This patch adds a method `startListeningUnix` to `Server` that lets the server listen on unix domain sockets as well as internet sockets.
My motivation for the patch is that I will have many servers running (one for each customer) and rather than allocate port numbers for each one and maintain a mapping from customer ID to port number, I would rather use the filesystem hierarchy for this organisation. I will use nginx to reverse proxy the connections to Seasocks.
The info line that Seasocks logs:
info: Listening on unix socket: http://unix:/var/eventstore/ws.socket
is nginx-compatible, ie:
location /ws/ {
proxy_pass http://unix:/var/eventstore/ws.socket;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header …
=> Support listening on AF_UNIX sockets

src/main/c/Server.cpp, src/main/c/seasocks/Server.h
State-Enum changed to scoped enum. As the enum is used internally only, there's no API change.
@mattgodbolt There are still some non-scoped enums left. Though changing them to scoped could case an API change as `log(DEBUG, "abc")` becomes `log(Level::DEBUG, "abc")`. Therefore I haven't changed them – what's your take on that?
=> Enum changed to scoped enum

src/app/c/ws_test.cpp, src/app/c/ws_test_poll.cpp, src/main/c/Server.cpp, src/main/c/internal/LogStream.h, src/main/c/seasocks/util/Json.h, src/test/c/ServerTests.cpp
Some shadowed variables fixed.
-----------------------
Unfortunately adding `-Wshadow` to the CI builds ends in blood and thunder, because all compiler at Travis will warn about methods hiding parameter with the same identifier.
=> Fixes for shadowed variables

CMakeLists.txt, src/main/web/CMakeLists.txt
Search and check python executable. This will cause an error if `python2` is not installed. In addition the path can be changed through command line / CMake Gui.
=> Search and check python executable

CMakeLists.txt, src/app/c/CMakeLists.txt, src/main/c/CMakeLists.txt, src/main/c/Connection.cpp, src/main/c/HybiPacketDecoder.cpp, src/main/c/Server.cpp, src/main/c/internal/HybiPacketDecoder.h, src/main/c/internal/ZlibContext.h, src/main/c/seasocks/Connection.h, src/main/c/seasocks/Server.h, src/test/c/CMakeLists.txt
Github issue #5
For my work-load (somewhat redundant JSON) it reduces the transmitted
message sizes to nearly 1/10th their uncompressed sizes so it will be
a huge bandwidth saver.
It basically does the bare minimum to be RFC 7692 compatible. I have
tested the compression with chromium and websocketpp 0.7.0 and seasocks
seems to compress/decompress messages properly in both directions.
Current limitations:
- Can't configure the *_no_context_takeover or *_max_window_bits
extensions. It will only negotiate the default (context takeover
and max window bits in both directions)
- All transmitted messages will be compressed. Ideally you should
be able to opt-out of compressing particular messages (but it
does support clients that compress particular messages)
- Only ever issues one DEFLATE block …
=> Per-message deflate as described in RFC 7692

.travis.yml
Clang 3.9 has finally been whitelisted by travis ci (https://github.com/travis-ci/apt-source-whitelist/issues/300).
=> Clang 3.9 has finally been whitelisted by travis ci

.travis.yml, src/test/c/MockServerImpl.h
1. Adds Clang 4.0 ci build (#64)
1. Fixes a build failure on all clang builds (missing `override`)
1. Fixes broken compiler selection on all ci builds (instead of the desired compiler, Gcc 4.8 was always used)
=> Clang 4.0 and some fixes

src/main/c/seasocks/ResponseBuilder.h, src/test/c/CMakeLists.txt, src/test/c/ResponseBuilderTests.cpp
Type deduction fixed (issue #66).
=> Type deduction fixed

src/main/c/Connection.cpp, src/main/c/seasocks/Connection.h
Forward declaration instead of include to break dependency to an internal header.
=> Forward declaration instead of include to break dependency

src/app/c/CMakeLists.txt, src/app/c/streaming_test.cpp, src/main/c/CMakeLists.txt, src/main/c/internal/ConcreteResponse.h, src/main/c/seasocks/Response.h, src/main/c/seasocks/ResponseWriter.h, src/main/c/seasocks/SimpleResponse.h, src/main/c/seasocks/StreamingResponse.cpp, src/main/c/seasocks/StreamingResponse.h
Hey guys!
I've added a new Response type which doesn't meddle with the before sending it (adding headers, sending errors in the error file template, etc.). It also uses streams to get data.
I plan to use this to remove assumptions the core makes (CORS enabled, Server Name, default file handling, error handling) to make seasocks more flexible while keeping seasocks easy to use.
=> Added StreamingResponse

src/main/c/CMakeLists.txt
Add SONAME versioning to shared library
Shared library files should include their version information, so that the runtime linker knows whether the installed shared library works with the program trying to use it. CMake supports this with the VERSION and SOVERSION properties for shared library targets.
This resolves #77 in the most conservative way possible (with the full version information going into the SONAME), because anything more would require stricter adherence to semantic versioning than this project has historically seen.
=> Add SONAME versioning to shared library

CMakeLists.txt, scripts/gen_embedded.py, src/main/web/CMakeLists.txt
Support for python3 (_only_). Unfortunately this breaks python2 compatibility because of this single line (`ord(x)` vs. `x`):
```py
print '' + "".join(["'\\x%02x'," % ord(x) for x in bytes[start:start+MAX_SLICE]])
```
```py
print('' + "".join(["'\\x%02x'," % x for x in bytes[start:start+MAX_SLICE]])) 
```
@mattgodbolt is there any way to get this around so we can support both versions?
-----------------------------------------------------------
=> Python3 support

src/app/c/CMakeLists.txt
This fixes the following errors when trying to build with CMake 3.12:
Error copying directory from "/home/neel/git/seasocks/src/ws_chatroom" to "/home/neel/git/seasocks/src/app/c/src/ws_chatroom_web".
All of these seem to fail on the latest version of CMake.
=> Update CMakeLists.txt to work on CMake 3.12

src/main/c/StringUtil.cpp
On Alpine Linux, strerror_r returns an int error code and not the buffer itself.
=> Return errbuf

src/main/c/util/Json.cpp, src/test/c/JsonTests.cpp
Implementation of the workaround for non-ascii characters (see #105).
=> Escaping for non-ascii characters

CMakeLists.txt, src/main/c/CMakeLists.txt
Back again with more cmake improvements, I've finally got to the point where I had to make install rules for my tracing framework [Scalopus](https://github.com/iwanders/scalopus/). I had fixed using Seasocks through `find_package` from the build tree with https://github.com/mattgodbolt/seasocks/pull/108, but hadn't tried compiling against an installed version of Seasocks yet. When I tried that my `find_package(Seasocks)` instruction failed. The current `make install` of Seasocks only installs the headers and the libraries. This PR adds installing a `SeasocksConfig.cmake` which allows cmake to find the installed `Seasocks` through `find_package`. To do this we rely on [install(EXPORT)](https://cmake.org/cmake/help/v3.3/command/install.html?highlight=install#installing-exports), this …
=> Provide SeasocksConfig.cmake files when installed.

CMakeLists.txt, src/CMakeLists.txt
Title pretty much explains it; provide an option to disable the example applications from the `app/c` folder. When used in an embedded project these are unnecessary.
I broke convention in the option naming and prefixed it with `SEASOCKS_`, this is because this avoids option name collisions with multiple embedded libraries in one cmake project.
=> Allow disabling the example applications.

CMakeLists.txt, src/main/c/Server.cpp
Two fixes for compiling with Ubuntu Eoan, which ships with gcc 9.
One fix is that we allow `python3` to be identified as the Python binary. Just `python` is not available by default, the `gen_embedded.py` script works in python3, so there is no reason not to use it if it is available.
Second fix is to resolve an ambiguous overload for `gettid` from the anonymous namespace;
```
/vagrant/ws/seasocks/src/main/c/Server.cpp: In member function ‘bool seasocks::Server::loop()’:
/vagrant/ws/seasocks/src/main/c/Server.cpp:408:24: error: call of overloaded ‘gettid()’ is ambiguous
408 |     _threadId = gettid();
|                        ^
In file included from /usr/include/unistd.h:1170,
from /vagrant/ws/seasocks/src/main/c/Server.cpp:49:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: …
```
=> Fixes for Ubuntu Eoan with gcc 9

src/main/c/Connection.cpp, src/main/c/seasocks/ResponseCodeDefs.h
Handling of missing or invalid `Sec-WebSocket-Version` header added (#131).
=> Handle exceptions of invalid WS versions

src/main/c/Server.cpp
`gettid()` is available with glibc 2.30 (fixes #138).
=> Use gettid() on glibc 2.30+

src/main/c/StringUtil.cpp
=> Fix issue where socket errors print gibberish

src/main/c/CMakeLists.txt
this commit adds versioning to libseasocks.so
before:
/usr/local/lib/
|-- libseasocks.so
after:
/usr/local/lib/
|-- libseasocks.so -> libseasocks.so.1.4.4
|-- libseasocks.so.1.4.4
=> versioned shared library

.github/workflows/ci.yml, .github/workflows/codeql.yml, scripts/ci_setup_clang.sh
Clang 12 has introduced a dependency to `libunwind-12-dev` recently. Additionally, the *checkout* step has switched to `main` as default branch.
=> clang-12 CI fix and GH Action upate

src/main/c/PageRequest.cpp
Thanks for a great library! I'm using it in a few applications at work and getting crashes due to internal vulnerability scans looking for exploitable applications using log4j. Returning 0 seems sensible as it's being done in the other failure cases here.
Allow non-numeric or overly large header values for Content-Length, returning 0 instead.
=> Handle non-numeric Content-Length header

src/main/c/PageRequest.cpp
`val` was used outside of it's scope.
=> Fix variable scope

src/main/c/md5/md5.cpp
Hi all,
Thanks for this great project!
Created this PR after initial discussion here:  https://github.com/mattgodbolt/seasocks/pull/165
My environment was Ubuntu 22.04, with the system clang14 package (Ubuntu clang version 14.0.0-1ubuntu1)
Before this change, this is the compile error:
```
/home/trigen/projects/build-config/seasocks/seasocks/src/main/c/md5/md5.cpp:190:25: error: performing pointer subtraction with a null pointer may have undefined behavior [-Werror,-Wnull-pointer-subtraction]
if (!((data - (const md5_byte_t*) 0) & 3)) {
^ ~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/main/c/CMakeFiles/seasocks.dir/build.make:146: src/main/c/CMakeFiles/seasocks.dir/md5/md5.cpp.o] Error 1
```
I researched it a little bit, found the PR I commented on previously, and further …
=> MD5: Removed null pointer subtraction

.github/workflows/ci.yml
Adds builds for latest Clang versions.
Both issue an error due to possible UB though:
```
/home/runner/work/seasocks/seasocks/src/main/c/md5/md5.cpp:190:25: error: performing pointer subtraction with a null pointer may have undefined behavior [-Werror,-Wnull-pointer-subtraction]
if (!((data - (const md5_byte_t*) 0) & 3)) {
^ ~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
=> Clang 13 and 14 CI builds

.github/workflows/ci.yml, .github/workflows/codeql.yml, scripts/ci_setup_clang.sh
Migration of GCC / Clang builds to Docker images. This enables eg. newer compiler version without messing with the host OS.
Additionally:
- GCC 12 added
- Update to `ubuntu-latest` (Runner)
- Update `setup-python` to `main` (instead of a fixed version)
- Migration to CodeCov Github Action
Please note: As before there's no coverage upload on Clang, since it doesn't produce data.
=> CI modernization

CMakeLists.txt, scripts/ci_setup_clang.sh
Fixes the `Could NOT find Threads (missing: Threads_FOUND)` error on Clang 14.
=> Require Threads package and add missing Clang 14 package

CMakeLists.txt
According to [CMake 3.27 release notes](https://cmake.org/cmake/help/latest/release/3.27.html#deprecated-and-removed-features):
> Compatibility with versions of CMake older than 3.5 is now deprecated and will be removed from a future version.
=> Require CMake 3.5+

src/main/c/HybiPacketDecoder.cpp, src/main/c/seasocks/StreamingResponse.cpp
This fixes compiler warnings treated as errors when compiling for x86 on Windows:
> D:\buildtrees\seasocks\src\v1.4.5-50543c2dd9.clean\src\main\c\seasocks\StreamingResponse.cpp(54): error C2220: the following warning is treated as an error
D:\buildtrees\seasocks\src\v1.4.5-50543c2dd9.clean\src\main\c\seasocks\StreamingResponse.cpp(54): warning C4244: 'argument': conversion from 'std::streamsize' to 'size_t', possible loss of data
> D:\buildtrees\seasocks\src\v1.4.5-50543c2dd9.clean\src\main\c\HybiPacketDecoder.cpp(86): error C2220: the following warning is treated as an error
D:\buildtrees\seasocks\src\v1.4.5-50543c2dd9.clean\src\main\c\HybiPacketDecoder.cpp(86): warning C4244: '=': conversion from 'uint64_t' to 'size_t', possible loss of data
=> Fix x86 build

.github/workflows/ci.yml
Clang 9 and 10 use an Ubuntu 18.04 based image, which isn't supported by the latest version of the checkout action.
https://github.com/actions/checkout/issues/1442
=> Drop compiler running on a deprecated (by GH actions) version of Ubuntu

.github/workflows/ci.yml
Adds a CI build for the latest Clang 18.
GCC 7 and 8 are based on an outdated image and their git installation doesn't seem to support features used by GH Actions. I suggest to drop them as they are quite old now.
=> CI builds: Add Clang 18, remove GCC 7/8

CMakeLists.txt
Would have saved me some time.
If you don't need deflate support and don't want to have to link zlib, so you get:
```
libseasocks.a(ZlibContext.cpp.o): in function `seasocks::ZlibContext::Impl::Impl(int, int, int)':
ZlibContext.cpp:(.text._ZN8seasocks11ZlibContext4ImplC2Eiii[_ZN8seasocks11ZlibContext4ImplC5Eiii]+0x98): undefined reference to `deflateInit2_'
```
you should cmake with `-DDEFLATE_SUPPORT=OFF` which takes a bit of reading to find. A cmake message makes it clear from the start.
=> add cmake message about zlib depend on deflate support
